format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Item"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
