[alias]
__vendored = [
    "--config",
    "source.crates-io.replace-with = \"vendored-sources\"",
    "--frozen",
    "--offline",
]

xr = "__vendored check --release --workspace --verbose --all-features --all-targets"
cr = "__vendored clippy --release --workspace --verbose --all-features --all-targets -- -D warnings"
br = "__vendored build --release --workspace --verbose"
rr = "__vendored run --release --workspace --verbose"
tr = "__vendored test --release --workspace --verbose"

xd = "__vendored check --verbose --workspace --all-features --all-targets"
cd = "__vendored clippy --verbose --workspace --all-features --all-targets -- -D warnings"
bd = "__vendored build --verbose --workspace"
rd = "__vendored run --verbose --workspace"
td = "__vendored test --verbose --workspace"

v = "vendor --verbose --versioned-dirs"

[source.vendored-sources]
directory = "vendor"
